update sonar scripts

diff --git a/Codigo/scripts/sonar b/Codigo/scripts/sonar
--- a/Codigo/scripts/sonar
+++ b/Codigo/scripts/sonar
@@ -70,9 +70,8 @@ docker run \
     -Dsonar.host.url="${SONAR_URL}"
 
 sleep 15
-if ! curl -s "${SONAR_URL}/api/issues/search?componentKeys=${PROJECT_KEY}&resolved=false&ps=1" | grep -q '{"total":0,' && \
-   ! curl -s "${SONAR_URL}/api/measures/component?component=${PROJECT_KEY}&metricKeys=coverage" | grep -q '"coverage","value":"100.0"'; then
-    echo "ERROR: SonarQube analysis failed. Issues found or code coverage is not 100%." >&2
+if ! curl -s "${SONAR_URL}/api/issues/search?componentKeys=${PROJECT_KEY}&resolved=false&ps=1" | grep -q '{"total":0,'; then
+    echo "ERROR: SonarQube analysis failed. Issues found." >&2
     echo "Check the SonarQube dashboard at ${SONAR_URL} for more details." >&2
     exit 1
 fi
